# Module 1.3 - Scientific Modules

## Table of content

1. [Table of content](#Table-of-content)
2. [Scientifics Modules](#Scientific-Modules)
    1. [NumPy](#NumPy)
      1. [ndarray](#ndarray)
          1. [creating and ndarray](#creating-an-ndarray)
          2. [working with ndarrays](#working-with-ndarrays)
          3. [NumPy and mathematics](#NumPy-and-mathematics) 
3. [Exercises](#Exercises)
    1. [Exercise 52 - NumPy arrays](#Exercise-52---NumPy-arrays)
    2. [Exercise 53 - Mathematics with NumPy](#Exercise-53---Mathematics-with-NumPy)

# Scientific Modules

## NumPy

*The* fundamental package for scientific computing.    
Includes among other things:
- the np.ndarray
- mathematical functions like np.sqrt()
- submodule np.linalg for linear algebra (to import a single submodule: `import numpy.linalg as linalg`)

Importing convention for NumPy: `import numpy as np`

It has it's own help page: https://numpy.org

In [1]:
#installed numpy through the terminal with the command `pip3 install numpy`

In [2]:
import numpy as np

### ndarray

Datastructure in NumPy which is used to model matrices and vectors

- fixed size at the creation, we cannot add or remove elements from an ndarray (but we can change them, e.g. when placing results inside)
- all elements have to be of the same type: all strings, all floats, all integers etc.

ndarrays look like lists in the print out, except they have no commas.   
ndarrays are of type numpy.ndarray

In [3]:
#create a small example ndarray
a1 = np.array([1,2,3,4])
print(a1)
print(type(a1))

[1 2 3 4]
<class 'numpy.ndarray'>


#### creating an ndarray

- lists, sets and tuples can be cast into an ndarray (as long as they only have one data type)    
  `np.array(list)`
- creating a range in the creation (follows the usual `range()` rules, but allows for floats)    
  `np.arange(start,stop,step)`
- creating an array with zeros, where x is the number of elements. x can be a tuple   
  `np.zeros(x)`
- creating an array with ones, where x is the number of elements. x can be a tuple       
  `np.ones(x)`
- creating an multidimensional arrays with a tuple, where x is the number of outside elements and y is the number of inside elements. Can have as many dimensions as needed/wanted   
  `np.zeros((x,y))`
- creating an array with random numbers taken from a normal distribution with mean 0 and stdev 1   
  `np.random.randn(x,y)`
- creating an array with x rows and y columns with random integers in the range between start and stop    
  `np.random.randint(start, stop, size=(x,y))`

Note: Multidimensional arrays are *always* rectangular, i.e. all elements in the outer part of the array have the exact same number of elements

In [4]:
print(np.arange(5,15,5))
print(np.zeros(3))
print(np.ones((2,3)))
print(np.random.randn(3,2))

[ 5 10]
[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[-1.54101971  1.4566511 ]
 [-0.6044626  -1.41569932]
 [ 1.03909306 -1.65168547]]


#### working with ndarrays

- all operations apply elementwise
- as long as two ndarrays have the same size I can freely sum up, substract, multiply them etc.
- basic ndarray functions, none of these work in-place:   
  `array.sum()` -> gives the total sum of the array   
  `arry.min()` -> gives the min value of the array   
  `arry.max()` -> gives the max value of the array   
  `array.transpose()` -> turns the array around (rows -> columns and columns-> rows), needs to be assigned to a variable if you want to work with it   
  `array.shape` -> without `()` as not a method!! Gives us back the shape of the array

We can call individual elements using `[idx]`, same as with lists.    
Multidimensional arrays are accessed with multiple `[]`:
`array[2][3]` calls the fourth element of the third element

#### NumPy and mathematics
There are a large number of mathematical operations we can use on arrays in NumPy.   

- All of these methods work elementwise.   
- If I want to work mathematics with two arrays they have to be of the *same dimension*
- some examples for function: `np.sin()`, `np.cos()`, `nplog()`, `np.log10()`, `np.exp()`, `np.power()`, `np.sqrt()` etc. etc.
- these functions are rather robust, even if a mathematical operation is not possible it continues and just returs `nan`

In [5]:
#create an example array
arrayA = np.random.randint(-10, 10, size=(2,3))
print(arrayA)

[[ -6  -7 -10]
 [ -7   0  -7]]


> mathematical operations with a single number work on all elements

In [6]:
print(arrayA)
arrayA4 = arrayA * 4
print(arrayA4)

[[ -6  -7 -10]
 [ -7   0  -7]]
[[-24 -28 -40]
 [-28   0 -28]]


> two arrays have to have the same size

In [7]:
arrayAb = arrayA - arrayA4
print(arrayAb)

[[18 21 30]
 [21  0 21]]


> the mathematical functions work on the whole array and are rather robust

In [8]:
print(arrayA)
print()
print(np.power(arrayA,2))
print()
print(np.sqrt(arrayA))

[[ -6  -7 -10]
 [ -7   0  -7]]

[[ 36  49 100]
 [ 49   0  49]]

[[nan nan nan]
 [nan  0. nan]]


/var/folders/pq/1h0dzqv16j58hqpqtlb29y280000gn/T/ipykernel_12788/151381962.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(arrayA))


# Exercises

## Exercise 52 - NumPy arrays
Write a simple python program that generates the following arrays:  

- An array consisting of 25 zeros
- An array consisting of 8 ones
- An array consisting of numbers from 0 to 24 in order
- An array consisting of 9 entries of your choice
- An two-dimensional array TD consisting of 6 rows of arrays with 5 entries each
- A transposed version of the two-dimensional array TD

Furthermore print out the sum, maximum value, minimum value and shape of all created arrays.

In [9]:
#creating the arrays, note: I use random.randint not random.randn simply for better readbility of the readout
array1 = np.zeros(25)
array2 = np.ones(8)
array3 = np.arange(25)
array4 = np.array([10, 3, 19.90, 16, 6, 20.22, 4, 3, 19.89])
arrayTD = np.random.randint(1, 100, size=(6,5))
arrayTD_t = arrayTD.transpose()

# I put all my arrays in a dictionary so I can loop the print command
arraydict = {"array1":array1,"array2":array2,"array3":array3,"array4":array4,"arrayTD":arrayTD,"arrayTD_t":arrayTD_t}

#loop of the print command. I use dict.items() to easily access both the name (= the key) and the arrays themselves
for name,ary in arraydict.items():
    print("####",name,"####")
    print(ary)
    print("sum:",ary.sum())
    print("max:",ary.max())
    print("min:",ary.min())
    print("shape:",ary.shape)
    print()

#### array1 ####
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
sum: 0.0
max: 0.0
min: 0.0
shape: (25,)

#### array2 ####
[1. 1. 1. 1. 1. 1. 1. 1.]
sum: 8.0
max: 1.0
min: 1.0
shape: (8,)

#### array3 ####
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
sum: 300
max: 24
min: 0
shape: (25,)

#### array4 ####
[10.    3.   19.9  16.    6.   20.22  4.    3.   19.89]
sum: 102.01
max: 20.22
min: 3.0
shape: (9,)

#### arrayTD ####
[[68 93 18 17 53]
 [53 93 44  5 76]
 [79 37 84 91 65]
 [ 1 49 35  9  9]
 [56 83 69 62 36]
 [14 49 17 40 41]]
sum: 1446
max: 93
min: 1
shape: (6, 5)

#### arrayTD_t ####
[[68 53 79  1 56 14]
 [93 93 37 49 83 49]
 [18 44 84 35 69 17]
 [17  5 91  9 62 40]
 [53 76 65  9 36 41]]
sum: 1446
max: 93
min: 1
shape: (5, 6)



## Exercise 53 - Mathematics with NumPy
Use the arrays from Exercise 52 and run some mathematical functions like np.sin with them. You can just add the calculations to your script from exercise 54. Don’t forget to print out the results.

In [10]:
print(np.log10(array3))

[      -inf 0.         0.30103    0.47712125 0.60205999 0.69897
 0.77815125 0.84509804 0.90308999 0.95424251 1.         1.04139269
 1.07918125 1.11394335 1.14612804 1.17609126 1.20411998 1.23044892
 1.25527251 1.2787536  1.30103    1.32221929 1.34242268 1.36172784
 1.38021124]


/var/folders/pq/1h0dzqv16j58hqpqtlb29y280000gn/T/ipykernel_12788/2386033878.py:1: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(array3))


In [11]:
print(np.exp(arrayTD))

[[3.40427605e+29 2.45124554e+40 6.56599691e+07 2.41549528e+07
  1.04137594e+23]
 [1.04137594e+23 2.45124554e+40 1.28516001e+19 1.48413159e+02
  1.01480039e+33]
 [2.03828107e+34 1.17191424e+16 3.02507732e+36 3.31740010e+39
  1.69488924e+28]
 [2.71828183e+00 1.90734657e+21 1.58601345e+15 8.10308393e+03
  8.10308393e+03]
 [2.09165950e+24 1.11286375e+36 9.25378173e+29 8.43835667e+26
  4.31123155e+15]
 [1.20260428e+06 1.90734657e+21 2.41549528e+07 2.35385267e+17
  6.39843494e+17]]


In [12]:
print(np.sqrt(arrayTD_t))

[[8.24621125 7.28010989 8.88819442 1.         7.48331477 3.74165739]
 [9.64365076 9.64365076 6.08276253 7.         9.11043358 7.        ]
 [4.24264069 6.63324958 9.16515139 5.91607978 8.30662386 4.12310563]
 [4.12310563 2.23606798 9.53939201 3.         7.87400787 6.32455532]
 [7.28010989 8.71779789 8.06225775 3.         6.         6.40312424]]
